inherit_from: .rubocop_todo.yml

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/EmptyLineBetweenDefs:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true
  EnforcedStyle: no_empty_lines

Layout/HashAlignment:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false
